theme: jekyll-theme-minimal
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onetitle: Digital Scholarship Workshop Series - Census Data in R
description: Jupyter Notebooks for exploring the practice and possibilities of using Census Data in R.
show_downloads: true # shows download links for the repository
logo: # can easily be replaced with an institutional logo by uploading a new file
google_analytics: [Your Google Analytics tracking ID]
